#include <iostream>
#include <vector>

using namespace std;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

unsigned long better_fib()
{
    unsigned long result = 0;

        vector<unsigned long> fib = { 0, 1 };
        unsigned long fibNum = 0;
        int i = 2;
        while (fibNum <= 4000000)
        {
            fibNum = fib[i - 1] + fib[i - 2];
            fib.push_back(fibNum);
            //cout << fibNum << endl;

            if (fibNum % 2 == 0)
            {
                result += fibNum;
                //cout << fibNum << " result:" << result << endl;
            }
            i++;
        }
    
    return result;

}

int main()
{
    unsigned long result = better_fib();
    cout << result;
    return 0;
}